language: php
php:
- 7.3
before_script:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- composer install
- cd web/app/themes/lumberjack
- npm i
- npm run build
after_success:
- cd $TRAVIS_BUILD_DIR
- rsync -avz --delete-after --exclude node_modules web/app/mu-plugins ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_HOST}/web/app
- rsync -avz --delete-after --exclude node_modules web/app/plugins ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_HOST}/web/app
- rsync -avz --delete-after --exclude node_modules web/app/themes ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_HOST}/web/app
- rsync -avz --delete-after web/wp ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_HOST}/web

notifications:
  email: false
env:
  global:
  - secure: ddAzIGGqQAH/dwOTS04veuPDJDoJs0laeZ3qI+jncnEyMWA5mULmyGkuMX3a7WEDfMJ2eg7s5zzfjWe4kYat8TtFEUUwKO5FhqosQUef9nzIiSrthaB7PsYwy5gKYdodZoeFkGkH1NkDEdgtIMtszqqEFBTkjGOqCa7N4kyC1YiZR+IQBSa+/i5AfT+iHY9f/v/f0e3fntWQ/TYHcDH5azGrbHd2fx7CoZh4WjCSke/FTKc2/rZzxyxxVBecTvI4mqu8Qd+tEf4mduDODDdIQ+sonMPJ//Xa/DYEBAsQ5C66mH4BnHbu9g/L+MIxZw2S4Fm63W5MZc0hdom+sgaQn8cRjLDxDC5kvS259STMkpvnH3pJ4jSHyxRlop41nQGa9kin8XnVxsQ6DNsQs9p6i0me81J7XgkEb4kL9TPbQjQcfXUzwj09DdCJEgKESSozNbkXTg/Kl9VLP8LDSFUBrkXqlGX0GaxPxsNtJOl2EDF4MSID9Fu70fOwHhMSK4ln+nBVHGhb6LOHSk4H/kQj5LbTZdD19KJ1YB+R2WZtH00e5a5ErjWHVZ5u1EKiykmF/yLG329FqEm/EBXa4Du6awjUxm7nL9+e4pwRuiUVaxy1wMVEYjdK8QznXikwhYaFwLWy7ktu08aoZrgzUi6h5yrdRAnDJR9jHyl0MVG1x4I=
  - secure: f+jgUuEUIPLjF9l8pga7nC01N8kWkZ6XPBpyEKmZX2L1z9Lk5d9vBjCuWjt/u9niTnAUuaeiOfbnhmS54O+duwJ1CAhP2+h6p8eUsssbjWHBXqXubNnVSOtTPHnr/lboHGbhDkxjFc2CzDQRyuN8bD7OQ7SzP83/gLvPn9UmoExmVFaHcwfgjMvVUF1/aTzhV+nyoKxAJZTeqM/EG+a5y9ahltuWKc4EmKSOJ/W01uzQmUK33DYlUw3gGcGIStuQMHzt+t7g+0sZ7eGdjsBNIOCv+meByL0SbrgpD+hpjJiPMk7AeTX7WoOdctLs21Scc37Rq36NSTZAUK//0Nx3QfAzPG0Z6Gw555V/vhTLnSNJkfj50z2z9v53dh+WOAT9oxGyite1igcxQabKwkoRvZwaES7dBwearW5Cov1zLi+K7d5+HIZauA142qWAQ492DfJs0gpo2mGsffbJm4CoHNjZ0//tBlxdLNG3VGLNPag3mqhPrX42c9gjpiE6yGuXjdzYoO/bSRhOVKp/P/iSFXwFDDBYe2tXeZEQFZIw+0c3yIDh/3Srzj94apMc/rPm3TtAWnIRpm4N9OZzjF7phHji89cSNSeTSXcAGWdF+oOsy9jso+Jsc9ieFHYgC/RviPEJMoabN6kIG+B6qXx192xu2a3xObx8k8qZfQ5zU+I=
  - secure: P4d6325DgfAzuhZ/BokA9SJZTvcv4xMMsKgXKEnDB8xUIDH1MoTubgHas+UneFPPQFMJ9CmNJGMdcDJJc2eVkENSl/sgrYOZpOoGNh6tw2b5rqvrR571RtMWbi4jMM+lYgoc3zYu+6n8r3RnwwaUgJ1ZZOyscwvB1ilr9k6uKsIkwQ3u64nqWYHZe/HX4H9Lh7GCYrCYUfyzTUinQ/AXywHCe6jx20xz53i8EFBspdkJCx4QS4Xy6A1G4N5Q64qlNw3mgEtJpdj7c0wbyM02qawYlNAHUi3XRNxN+6KhkEsF81O//+e/xwFFoEj58LsvTInTpQGnFPLtd3r5EaHQjaPyLl17yZYff5Nz+0TKnmrpeeVsWqhunptclDrayQcyoowMfPdId93IYm8nzhOgLXEHzqI7l/3LO4vP+x3s1sLvsXSSzweH5ay3t5ye/ovrtLJR034x15uUQoRPZCYVej9yQJcC9JGn2Ig5/RAk3Y8ulqEiWXexv4ljaVlaJkV+4TKaUH8Np1/SSt7mLhZguB6K3aOTuIXzAT4eIfLKipurpaTzTPtp1SLA806vCrYgFpGD+SNdiSD7seTapO93t3YO2M2bOQb3Dwu9/feYTh8ZilA308giYWD2/J3vqSa1liLA2bmqycyIMxYgNHDlmQOnrwhIibgi3QgN5y+iqGA=
  - secure: atIlpOPwfYkbs0ENZwAi0qj44pocTV37mZLr+Wyq6SfkbSOrlLHZ8lHCBx1d8xusYPagcI+h1beOhixdYbmn2fsM7uFYZGrUtPpt/TIbzM1xJl+RFBVnBHaW0U0yE/lOqDBAK/fUF3Vn4DnEl1ZJ6nljHuvCQ31RCHtoZcgz1PjGo/Jq7HUwT9LWBWEayWXwBtTdmDrDEDTa18wZBIs6ECHMio7lrUnu5WfKIjVrtCteMSiW2KfVXVz/7mpWKgQeqfBDpHRepbHi5d6EaHHUK701LQyYzW7azKrceP0D+dhp9s94540AP0K6WoDSd7hUMinQbN4zl1zHGNJhpZH019X0pWsCym9cfU+0lhCwaDt/gD+AdA1NEhu5HH6UdIAMDuhlEKfHO6OcvV7gr5WoDNaUOj43IVfP/fVQwhZESd69yEEII7cr6skkOPM1TA29Jn4N6+I16q+/3ZTEnjNlGBS7XszgKb1waXMOaauuJCoqHWA/MsKdeTg85A3+tHRYVcqjo1M4mJJsb163iPrfASVxsPalQgjTVd44Zrg43W1D5Rwp+BSncFhX4Ai6Lf5b9cnc/Ju1GVYlARnit+G5YN2IUjh5aUzNqZ+cU1O86m801loInuvWml7hhLY8MN/VLlSG87lutGnLu2Ai7rMPvEOoKeaYKHC15XpfiHJN1I8=
